import { useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, Calculator, Camera, ChevronRight, History, Pencil, Plus, Search, Trash2, Utensils, X } from "lucide-react";
import { toast } from "sonner";
import { Button, EmptyState, Field, Modal, Pill, Spinner } from "@/components/kit";
import { StoredImage } from "@/components/StoredImage";
import { supabase } from "@/integrations/supabase/client";
import { calculateFoodCarbs, calculateInsulin, formatDecimal, parseDecimal } from "@/lib/meal-calculator";
import { DEFAULT_SETTINGS, useSettings } from "@/lib/settings";
import { compressImage, uploadFile } from "@/lib/storage";
import { formatDateTime } from "@/lib/format";

type Food = { id: string; name: string; category: string; carbs_per_100g: number; brand: string | null; notes: string | null; image_url: string | null; active: boolean };
type SelectedFood = Food & { key: string; weight: string };
type MealItem = { id: string; food_name_snapshot: string; brand_snapshot: string | null; weight_grams: number; carbs_per_100g_snapshot: number; calculated_carbs: number };
type Meal = { id: string; created_at: string; created_by_name: string; glucose: number; total_carbs: number; meal_insulin: number; correction_insulin: number; total_dose: number; adjusted_dose: number | null; parameters_used: unknown; meal_items: MealItem[] };
type FoodDraft = { id?: string; name: string; category: string; carbs: string; brand: string; notes: string; image_url: string | null; active: boolean };
const blankFood: FoodDraft = { name: "", category: "", carbs: "", brand: "", notes: "", image_url: null, active: true };
const SAFETY = "Esta calculadora realiza apenas cálculos com base nos parâmetros cadastrados. Confirme os parâmetros e o resultado de acordo com a orientação da equipe de saúde antes de administrar qualquer dose.";

export function IsisScreen({ userName }: { userName: string }) {
  const [section, setSection] = useState<"calculator" | "foods" | "history">("calculator");
  return <div className="space-y-4"><div className="grid grid-cols-3 gap-2">
    <Button size="sm" variant={section === "calculator" ? "primary" : "outline"} onClick={() => setSection("calculator")}><Calculator className="h-4 w-4" />Calcular</Button>
    <Button size="sm" variant={section === "foods" ? "primary" : "outline"} onClick={() => setSection("foods")}><Utensils className="h-4 w-4" />Alimentos</Button>
    <Button size="sm" variant={section === "history" ? "primary" : "outline"} onClick={() => setSection("history")}><History className="h-4 w-4" />Histórico</Button>
  </div>{section === "calculator" && <CalculatorView userName={userName} />}{section === "foods" && <FoodsView />}{section === "history" && <MealHistory />}</div>;
}

function useFoods() { return useQuery({ queryKey: ["foods"], queryFn: async () => { const { data, error } = await supabase.from("foods").select("*").order("name"); if (error) throw error; return (data ?? []) as Food[]; } }); }

function CalculatorView({ userName }: { userName: string }) {
  const { data: foods = [] } = useFoods(); const { data: settings } = useSettings(); const qc = useQueryClient();
  const [glucose, setGlucose] = useState(""); const [search, setSearch] = useState(""); const [items, setItems] = useState<SelectedFood[]>([]); const [saving, setSaving] = useState(false);
  const activeFoods = foods.filter((food) => food.active && (!search || `${food.name} ${food.brand ?? ""} ${food.category}`.toLowerCase().includes(search.toLowerCase())));
  const params = { insulinCarbRatio: settings?.insulin_carb_ratio ?? DEFAULT_SETTINGS.insulin_carb_ratio, targetGlucose: settings?.target_glucose ?? DEFAULT_SETTINGS.target_glucose, correctionFactor: settings?.correction_factor ?? DEFAULT_SETTINGS.correction_factor, doseIncrement: settings?.dose_increment ?? DEFAULT_SETTINGS.dose_increment };
  const itemCarbs = items.map((item) => { const weight = parseDecimal(item.weight); return Number.isFinite(weight) && weight > 0 ? calculateFoodCarbs(weight, Number(item.carbs_per_100g)) : 0; });
  const glucoseNumber = parseDecimal(glucose); const valid = items.length > 0 && items.every((item) => parseDecimal(item.weight) > 0) && glucoseNumber > 0 && glucoseNumber <= 1000;
  const calculation = valid ? calculateInsulin(itemCarbs, glucoseNumber, params) : null;
  function add(food: Food) { setItems((current) => [...current, { ...food, key: crypto.randomUUID(), weight: "" }]); setSearch(""); }
  async function saveMeal() {
    if (!calculation) return toast.error("Informe a glicemia e o peso de todos os alimentos");
    if (glucoseNumber < 70 && !confirm("A glicemia informada está abaixo de 70 mg/dL. Confirme com sua orientação de saúde antes de continuar. Deseja apenas salvar este cálculo?")) return;
    if (calculation.adjustedDose > 20 && !confirm(`A dose ajustada é ${formatDecimal(calculation.adjustedDose, 2)} U. Confirme se os dados estão corretos antes de salvar.`)) return;
    setSaving(true);
    const parameters_used = { insulin_carb_ratio: params.insulinCarbRatio, target_glucose: params.targetGlucose, correction_factor: params.correctionFactor, dose_increment: params.doseIncrement };
    const { data: meal, error } = await supabase.from("meals").insert({ created_by_name: userName, glucose: glucoseNumber, total_carbs: calculation.totalCarbs, meal_insulin: calculation.mealInsulin, correction_insulin: calculation.correctionInsulin, total_dose: calculation.totalDose, adjusted_dose: calculation.adjustedDose, parameters_used }).select("id").single();
    if (error || !meal) { setSaving(false); return toast.error(error?.message ?? "Não consegui salvar"); }
    const { error: itemError } = await supabase.from("meal_items").insert(items.map((item, index) => ({ meal_id: meal.id, food_id: item.id, food_name_snapshot: item.name, brand_snapshot: item.brand, weight_grams: parseDecimal(item.weight), carbs_per_100g_snapshot: Number(item.carbs_per_100g), calculated_carbs: itemCarbs[index] ?? 0 })));
    if (itemError) { await supabase.from("meals").delete().eq("id", meal.id); setSaving(false); return toast.error(itemError.message); }
    setItems([]); setGlucose(""); setSaving(false); await qc.invalidateQueries({ queryKey: ["meals"] }); toast.success("Refeição salva no histórico");
  }
  return <div className="space-y-4">
    <section className="surface p-4"><Field label="Glicemia atual (mg/dL)"><input className="field" inputMode="decimal" placeholder="Ex.: 174" value={glucose} onChange={(e) => setGlucose(e.target.value)} /></Field>{glucoseNumber > 0 && glucoseNumber < 70 && <p className="mt-2 text-xs font-semibold text-destructive">Glicemia abaixo de 70 mg/dL. Siga a orientação da sua equipe de saúde.</p>}</section>
    <section className="surface p-4"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><input className="field pl-9" placeholder="Pesquisar alimento para adicionar" value={search} onChange={(e) => setSearch(e.target.value)} /></div>
      {search && <div className="mt-2 max-h-52 space-y-1 overflow-y-auto">{activeFoods.slice(0, 20).map((food) => <button key={food.id} className="flex w-full items-center justify-between rounded-xl p-2 text-left hover:bg-secondary" onClick={() => add(food)}><span><strong className="block text-sm">{food.name}</strong><small className="text-muted-foreground">{food.brand ? `${food.brand} · ` : ""}{formatDecimal(Number(food.carbs_per_100g))} g / 100 g</small></span><Plus className="h-4 w-4 text-primary" /></button>)}{!activeFoods.length && <p className="p-3 text-center text-sm text-muted-foreground">Nenhum alimento ativo encontrado.</p>}</div>}
    </section>
    {!items.length && <EmptyState>Adicione um alimento e informe o peso consumido.</EmptyState>}
    {items.map((item, index) => <article key={item.key} className="surface p-3"><div className="flex items-start gap-3"><div className="min-w-0 flex-1"><strong className="block truncate text-sm">{item.name}</strong><span className="text-xs text-muted-foreground">{formatDecimal(Number(item.carbs_per_100g))} g de carboidrato / 100 g</span></div><Button size="icon" variant="ghost" aria-label="Remover alimento" onClick={() => setItems((current) => current.filter((entry) => entry.key !== item.key))}><X className="h-4 w-4 text-destructive" /></Button></div><div className="mt-3 grid grid-cols-2 gap-3"><Field label="Peso consumido (g)"><input className="field" inputMode="decimal" placeholder="0" value={item.weight} onChange={(e) => setItems((current) => current.map((entry) => entry.key === item.key ? { ...entry, weight: e.target.value } : entry))} /></Field><div><p className="text-xs font-semibold uppercase text-muted-foreground">Carboidratos</p><p className="mt-2 font-semibold text-primary">{formatDecimal(itemCarbs[index] ?? 0)} g</p></div></div></article>)}
    {calculation && <section className="surface p-4"><h3 className="mb-3">Resultado do cálculo</h3><Result label="Total de carboidratos" value={`${formatDecimal(calculation.totalCarbs)} g`} /><Result label="Insulina da refeição" value={`${formatDecimal(calculation.mealInsulin, 2)} U`} /><Result label="Insulina de correção" value={`${formatDecimal(calculation.correctionInsulin, 2)} U`} /><Result label="Dose calculada" value={`${formatDecimal(calculation.totalDose, 2)} U`} strong /><div className="mt-3 rounded-xl bg-primary-soft p-3"><Result label={`Dose ajustada (${formatDecimal(params.doseIncrement, 2)} U)`} value={`${formatDecimal(calculation.adjustedDose, 2)} U`} strong /></div></section>}
    <div className="rounded-xl border border-warning bg-warning/10 p-3 text-xs text-foreground"><div className="flex gap-2"><AlertTriangle className="h-4 w-4 shrink-0 text-warning" /><p>{SAFETY}</p></div></div>
    <Button className="w-full" disabled={!calculation || saving} onClick={() => void saveMeal()}>{saving ? <Spinner /> : <History className="h-4 w-4" />}Salvar no histórico</Button>
  </div>;
}

function Result({ label, value, strong = false }: { label: string; value: string; strong?: boolean }) { return <div className="flex items-center justify-between gap-3 py-1.5"><span className="text-sm text-muted-foreground">{label}</span><span className={strong ? "font-bold text-primary" : "font-semibold"}>{value}</span></div>; }

function FoodsView() {
  const { data: foods = [], isLoading } = useFoods(); const qc = useQueryClient(); const [search, setSearch] = useState(""); const [draft, setDraft] = useState<FoodDraft | null>(null);
  const filtered = foods.filter((food) => `${food.name} ${food.brand ?? ""} ${food.category}`.toLowerCase().includes(search.toLowerCase()));
  async function remove(food: Food) { if (!confirm(`Excluir “${food.name}”? O histórico já salvo será mantido.`)) return; const { error } = await supabase.from("foods").delete().eq("id", food.id); if (error) return toast.error(error.message); await qc.invalidateQueries({ queryKey: ["foods"] }); toast.success("Alimento excluído"); }
  return <div className="space-y-3"><div className="surface p-3"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><input className="field pl-9" placeholder="Nome, marca ou categoria" value={search} onChange={(e) => setSearch(e.target.value)} /></div><Button className="mt-3" size="sm" onClick={() => setDraft({ ...blankFood })}><Plus className="h-4 w-4" />Novo alimento</Button></div>
    {isLoading && <EmptyState>Carregando alimentos...</EmptyState>}{!isLoading && !filtered.length && <EmptyState>Nenhum alimento cadastrado.</EmptyState>}
    {filtered.map((food) => <article key={food.id} className="surface flex items-center gap-3 p-3"><StoredImage bucket="food-images" path={food.image_url} alt={food.name} className="h-14 w-14 shrink-0 rounded-xl" fallback={<Utensils className="h-5 w-5" />} /><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-1"><strong className="truncate">{food.name}</strong>{!food.active && <Pill tone="muted">inativo</Pill>}</div><p className="text-xs text-muted-foreground">{food.brand ? `${food.brand} · ` : ""}{food.category}</p><p className="text-sm font-semibold text-primary">{formatDecimal(Number(food.carbs_per_100g))} g / 100 g</p></div><div className="flex"><Button size="icon" variant="ghost" aria-label="Editar" onClick={() => setDraft({ id: food.id, name: food.name, category: food.category, carbs: String(food.carbs_per_100g), brand: food.brand ?? "", notes: food.notes ?? "", image_url: food.image_url, active: food.active })}><Pencil className="h-4 w-4" /></Button><Button size="icon" variant="ghost" aria-label="Excluir" onClick={() => void remove(food)}><Trash2 className="h-4 w-4 text-destructive" /></Button></div></article>)}
    <FoodModal draft={draft} onClose={() => setDraft(null)} onSaved={() => qc.invalidateQueries({ queryKey: ["foods"] })} />
  </div>;
}

function FoodModal({ draft, onClose, onSaved }: { draft: FoodDraft | null; onClose: () => void; onSaved: () => Promise<unknown> }) {
  const [form, setForm] = useState<FoodDraft>(blankFood); const [busy, setBusy] = useState(false);
  useMemo(() => { if (draft) setForm(draft); }, [draft]);
  async function save() { const carbs = parseDecimal(form.carbs); if (!form.name.trim() || !form.category.trim()) return toast.error("Informe nome e categoria"); if (!Number.isFinite(carbs) || carbs < 0 || carbs > 100) return toast.error("Informe carboidratos entre 0 e 100 g"); setBusy(true); const payload = { name: form.name.trim(), category: form.category.trim(), carbs_per_100g: carbs, brand: form.brand.trim() || null, notes: form.notes.trim() || null, image_url: form.image_url, active: form.active }; const query = form.id ? supabase.from("foods").update(payload).eq("id", form.id) : supabase.from("foods").insert(payload); const { error } = await query; setBusy(false); if (error) return toast.error(error.message); await onSaved(); onClose(); toast.success("Alimento salvo"); }
  async function image(file: File) { setBusy(true); try { const blob = await compressImage(file); const path = await uploadFile("food-images", blob); setForm((current) => ({ ...current, image_url: path })); } catch (error) { toast.error(error instanceof Error ? error.message : "Não consegui enviar a foto"); } finally { setBusy(false); } }
  return <Modal open={!!draft} onClose={onClose} title={form.id ? "Editar alimento" : "Novo alimento"} footer={<><Button onClick={() => void save()} disabled={busy}>{busy ? <Spinner /> : null}Salvar alimento</Button><Button variant="ghost" onClick={onClose}>Cancelar</Button></>}><Field label="Nome"><input className="field" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Field><div className="grid grid-cols-2 gap-3"><Field label="Carboidratos / 100 g"><input className="field" inputMode="decimal" placeholder="Ex.: 28" value={form.carbs} onChange={(e) => setForm({ ...form, carbs: e.target.value })} /></Field><Field label="Categoria"><input className="field" placeholder="Ex.: Cereais" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} /></Field></div><Field label="Marca (opcional)"><input className="field" value={form.brand} onChange={(e) => setForm({ ...form, brand: e.target.value })} /></Field><Field label="Observações"><textarea className="field min-h-20" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></Field><div className="flex items-center gap-2"><label className="inline-flex h-11 cursor-pointer items-center gap-2 rounded-xl border border-border bg-card px-4 text-sm font-semibold"><Camera className="h-4 w-4" />Foto<input type="file" accept="image/*" className="hidden" onChange={(e) => { const file = e.target.files?.[0]; if (file) void image(file); }} /></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.active} onChange={(e) => setForm({ ...form, active: e.target.checked })} />Alimento ativo</label></div></Modal>;
}

function MealHistory() {
  const [selected, setSelected] = useState<Meal | null>(null); const { data: meals = [], isLoading } = useQuery({ queryKey: ["meals"], queryFn: async () => { const { data, error } = await supabase.from("meals").select("*, meal_items(*)").order("created_at", { ascending: false }); if (error) throw error; return (data ?? []) as Meal[]; } });
  return <div className="space-y-2">{isLoading && <EmptyState>Carregando histórico...</EmptyState>}{!isLoading && !meals.length && <EmptyState>Nenhuma refeição salva.</EmptyState>}{meals.map((meal) => <button key={meal.id} onClick={() => setSelected(meal)} className="surface flex w-full items-center gap-3 p-3 text-left"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-primary-soft text-primary"><Utensils className="h-5 w-5" /></div><div className="min-w-0 flex-1"><strong className="block">{formatDecimal(Number(meal.total_carbs))} g de carboidratos</strong><p className="text-xs text-muted-foreground">{formatDateTime(meal.created_at)} · {meal.created_by_name}</p><p className="text-xs">Glicemia {formatDecimal(Number(meal.glucose), 0)} mg/dL · Dose {formatDecimal(Number(meal.adjusted_dose ?? meal.total_dose), 2)} U</p></div><ChevronRight className="h-4 w-4 text-muted-foreground" /></button>)}<MealDetail meal={selected} onClose={() => setSelected(null)} /></div>;
}

function MealDetail({ meal, onClose }: { meal: Meal | null; onClose: () => void }) {
  if (!meal) return null; const p = (meal.parameters_used && typeof meal.parameters_used === "object" ? meal.parameters_used : {}) as Record<string, unknown>;
  return <Modal open title="Detalhes da refeição" onClose={onClose}><p className="text-xs text-muted-foreground">{formatDateTime(meal.created_at)} · {meal.created_by_name}</p><div className="space-y-2">{meal.meal_items.map((item) => <div key={item.id} className="rounded-xl bg-secondary p-3"><strong className="text-sm">{item.food_name_snapshot}{item.brand_snapshot ? ` · ${item.brand_snapshot}` : ""}</strong><p className="text-xs text-muted-foreground">{formatDecimal(Number(item.weight_grams))} g × {formatDecimal(Number(item.carbs_per_100g_snapshot))} g/100 g</p><p className="text-sm font-semibold text-primary">{formatDecimal(Number(item.calculated_carbs))} g de carboidratos</p></div>)}</div><div className="border-t border-border pt-2"><Result label="Glicemia" value={`${formatDecimal(Number(meal.glucose), 0)} mg/dL`} /><Result label="Total de carboidratos" value={`${formatDecimal(Number(meal.total_carbs))} g`} /><Result label="Insulina da refeição" value={`${formatDecimal(Number(meal.meal_insulin), 2)} U`} /><Result label="Correção" value={`${formatDecimal(Number(meal.correction_insulin), 2)} U`} /><Result label="Dose calculada" value={`${formatDecimal(Number(meal.total_dose), 2)} U`} strong /><Result label="Dose ajustada" value={`${formatDecimal(Number(meal.adjusted_dose ?? meal.total_dose), 2)} U`} strong /></div><div className="rounded-xl bg-secondary p-3 text-xs"><strong>Parâmetros usados</strong><p>Relação: {String(p["insulin_carb_ratio"] ?? "—")} g/U · Alvo: {String(p["target_glucose"] ?? "—")} mg/dL</p><p>Fator: {String(p["correction_factor"] ?? "—")} mg/dL/U · Incremento: {String(p["dose_increment"] ?? "—")} U</p></div><div className="rounded-xl border border-warning bg-warning/10 p-3 text-xs"><AlertTriangle className="mr-2 inline h-4 w-4 text-warning" />{SAFETY}</div></Modal>;
}